// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuezalliApi.Models;

#nullable disable

namespace QuezalliApi.Migrations
{
    [DbContext(typeof(QuetzalliDBContext))]
    partial class QuetzalliDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuezalliApi.Models.Aviso", b =>
                {
                    b.Property<int>("Idavisos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idavisos");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idavisos"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("estatus");

                    b.Property<decimal>("NivelMinimoExistencias")
                        .HasColumnType("decimal(5,0)")
                        .HasColumnName("nivelMinimoExistencias");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int")
                        .HasColumnName("prioridad");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("titulo");

                    b.HasKey("Idavisos")
                        .HasName("PK_avisos_idavisos");

                    b.ToTable("avisos", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.AvisosInsumo", b =>
                {
                    b.Property<int>("IdavisosProductos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idavisos_productos");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdavisosProductos"), 1L, 1);

                    b.Property<int>("Idaviso")
                        .HasColumnType("int")
                        .HasColumnName("idaviso");

                    b.Property<int>("Idinsumos")
                        .HasColumnType("int")
                        .HasColumnName("idinsumos");

                    b.HasKey("IdavisosProductos")
                        .HasName("PK_avisos_insumos_idavisos_productos");

                    b.ToTable("avisos_insumos", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.AvisosProducto", b =>
                {
                    b.Property<int>("IdavisosProductos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idavisos_productos");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdavisosProductos"), 1L, 1);

                    b.Property<int>("Idaviso")
                        .HasColumnType("int")
                        .HasColumnName("idaviso");

                    b.Property<int>("Idproducto")
                        .HasColumnType("int")
                        .HasColumnName("idproducto");

                    b.HasKey("IdavisosProductos")
                        .HasName("PK_avisos_productos_idavisos_productos");

                    b.ToTable("avisos_productos", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.Bitacora", b =>
                {
                    b.Property<int>("Idbitacora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idbitacora");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idbitacora"), 1L, 1);

                    b.Property<DateTime>("Fecha")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("modulo");

                    b.Property<string>("Movimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("movimiento");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.HasKey("Idbitacora")
                        .HasName("PK_bitacora_idbitacora");

                    b.ToTable("bitacora", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.Cliente", b =>
                {
                    b.Property<int>("Idcliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idcliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idcliente"), 1L, 1);

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("idPersona");

                    b.HasKey("Idcliente")
                        .HasName("PK_cliente_idcliente");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idEmpleados");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleados"), 1L, 1);

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("idPersona");

                    b.Property<int>("IdPuesto")
                        .HasColumnType("int")
                        .HasColumnName("idPuesto");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("rfc");

                    b.HasKey("IdEmpleados")
                        .HasName("PK_empleado_idEmpleados");

                    b.ToTable("empleado", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.Horario", b =>
                {
                    b.Property<int>("Idhorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idhorario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idhorario"), 1L, 1);

                    b.Property<DateTime>("HoraFin")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("horaFin");

                    b.Property<DateTime>("HoraInicio")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("horaInicio");

                    b.HasKey("Idhorario")
                        .HasName("PK_horario_idhorario");

                    b.ToTable("horario", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.Insumo", b =>
                {
                    b.Property<int>("Idinsumo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idinsumo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idinsumo"), 1L, 1);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("idStock");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("estatus");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("idProveedor");

                    b.Property<string>("NombreInsumo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombreInsumo");

                    b.Property<float>("Precio")
                        .HasColumnType("real")
                        .HasColumnName("precio");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("unidad");

                    b.HasKey("Idinsumo")
                        .HasName("PK_insumo_idinsumo");

                    b.ToTable("insumo", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.InsumoLote", b =>
                {
                    b.Property<int>("IdproductoLote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idproducto_lote");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdproductoLote"), 1L, 1);

                    b.Property<int>("IdInsumo")
                        .HasColumnType("int")
                        .HasColumnName("idInsumo");

                    b.Property<int>("IdLote")
                        .HasColumnType("int")
                        .HasColumnName("idLote");

                    b.HasKey("IdproductoLote")
                        .HasName("PK_insumo_lote_idproducto_lote");

                    b.ToTable("insumo_lote", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.Libroreceta", b =>
                {
                    b.Property<int>("IdlibroRecetas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idlibroRecetas");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdlibroRecetas"), 1L, 1);

                    b.Property<float?>("CantidadInsumo")
                        .HasColumnType("real")
                        .HasColumnName("cantidadInsumo");

                    b.Property<int>("IdInsumo")
                        .HasColumnType("int")
                        .HasColumnName("idInsumo");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("idProducto");

                    b.HasKey("IdlibroRecetas")
                        .HasName("PK_librorecetas_idlibroRecetas");

                    b.ToTable("librorecetas", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.Lote", b =>
                {
                    b.Property<int>("IdstockInsumo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idstockInsumo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdstockInsumo"), 1L, 1);

                    b.Property<float>("Cantidad")
                        .HasColumnType("real")
                        .HasColumnName("cantidad");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("estatus");

                    b.Property<DateTime>("FechaCaducidad")
                        .HasColumnType("date")
                        .HasColumnName("fechaCaducidad");

                    b.Property<DateTime>("FechaObtencion")
                        .HasColumnType("date")
                        .HasColumnName("fechaObtencion");

                    b.Property<string>("NoLote")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("noLote");

                    b.Property<string>("Obesrvaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("obesrvaciones");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("unidad");

                    b.HasKey("IdstockInsumo")
                        .HasName("PK_lote_idstockInsumo");

                    b.ToTable("lote", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.Mesa", b =>
                {
                    b.Property<int>("Idmesas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idmesas");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idmesas"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("nombre");

                    b.HasKey("Idmesas")
                        .HasName("PK_mesa_idmesas");

                    b.ToTable("mesa", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.OrdenVenta", b =>
                {
                    b.Property<int>("IdordenVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idorden_venta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdordenVenta"), 1L, 1);

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("estatus");

                    b.Property<DateTime>("FechaVenta")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fechaVenta");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("idEmpleado");

                    b.HasKey("IdordenVenta")
                        .HasName("PK_orden_venta_idorden_venta");

                    b.ToTable("orden_venta", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.OrdenVentaProducto", b =>
                {
                    b.Property<int>("IdordenVentaProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idorden_venta_producto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdordenVentaProducto"), 1L, 1);

                    b.Property<float>("Cantidad")
                        .HasColumnType("real")
                        .HasColumnName("cantidad");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("estatus");

                    b.Property<int>("IdOrdenVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_orden_venta");

                    b.Property<int>("Idproducto")
                        .HasColumnType("int")
                        .HasColumnName("idproducto");

                    b.Property<DateTime>("Unidad")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("unidad");

                    b.HasKey("IdordenVentaProducto")
                        .HasName("PK_orden_venta_producto_idorden_venta_producto");

                    b.ToTable("orden_venta_producto", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.Pedido", b =>
                {
                    b.Property<int>("IdPedidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPedidos");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedidos"), 1L, 1);

                    b.Property<int>("Codigo")
                        .HasColumnType("int")
                        .HasColumnName("codigo");

                    b.Property<int>("Estatus")
                        .HasColumnType("int")
                        .HasColumnName("estatus");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fechaEntrega");

                    b.Property<DateTime>("FechaPedido")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fechaPedido");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("idCliente");

                    b.HasKey("IdPedidos")
                        .HasName("PK_pedido_idPedidos");

                    b.ToTable("pedido", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.PedidoProducto", b =>
                {
                    b.Property<int>("IdpedidoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idpedido_producto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdpedidoProducto"), 1L, 1);

                    b.Property<float>("Cantidad")
                        .HasColumnType("real")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdPedidos")
                        .HasColumnType("int")
                        .HasColumnName("idPedidos");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("idProducto");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("unidad");

                    b.HasKey("IdpedidoProducto")
                        .HasName("PK_pedido_producto_idpedido_producto");

                    b.ToTable("pedido_producto", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.Persona", b =>
                {
                    b.Property<int>("Idpersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idpersona");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idpersona"), 1L, 1);

                    b.Property<string>("ApellidoM")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellidoM");

                    b.Property<string>("ApellidoP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellidoP");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("telefono");

                    b.HasKey("Idpersona")
                        .HasName("PK_persona_idpersona");

                    b.ToTable("persona", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.Producto", b =>
                {
                    b.Property<int>("Idproductos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idproductos");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idproductos"), 1L, 1);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<float>("CostoProduccion")
                        .HasColumnType("real")
                        .HasColumnName("costoProduccion");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("estatus");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("foto");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("nombreProducto");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.Property<float>("PrecioVenta")
                        .HasColumnType("real")
                        .HasColumnName("precioVenta");

                    b.HasKey("Idproductos")
                        .HasName("PK_producto_idproductos");

                    b.ToTable("producto", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.ProductoLote", b =>
                {
                    b.Property<int>("IdproductoLote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idproducto_lote");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdproductoLote"), 1L, 1);

                    b.Property<int>("IdLote")
                        .HasColumnType("int")
                        .HasColumnName("idLote");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("idProducto");

                    b.HasKey("IdproductoLote")
                        .HasName("PK_producto_lote_idproducto_lote");

                    b.ToTable("producto_lote", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.Proveedor", b =>
                {
                    b.Property<int>("Idproveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idproveedor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idproveedor"), 1L, 1);

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("correo");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("estatus");

                    b.Property<string>("NombreContacto")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("nombreContacto");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("nombreEmpresa");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("telefono");

                    b.HasKey("Idproveedor")
                        .HasName("PK_proveedor_idproveedor");

                    b.ToTable("proveedor", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.Puesto", b =>
                {
                    b.Property<int>("Idpuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idpuesto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idpuesto"), 1L, 1);

                    b.Property<string>("NombrePuesto")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("nombrePuesto");

                    b.HasKey("Idpuesto")
                        .HasName("PK_puesto_idpuesto");

                    b.ToTable("puesto", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.Reservacion", b =>
                {
                    b.Property<int>("Idreservacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idreservacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idreservacion"), 1L, 1);

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("idCliente");

                    b.Property<int>("IdHorario")
                        .HasColumnType("int")
                        .HasColumnName("idHorario");

                    b.Property<int>("IdMesa")
                        .HasColumnType("int")
                        .HasColumnName("idMesa");

                    b.HasKey("Idreservacion")
                        .HasName("PK_reservacion_idreservacion");

                    b.ToTable("reservacion", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.Stock", b =>
                {
                    b.Property<int>("Idstock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idstock");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idstock"), 1L, 1);

                    b.Property<float>("CantidadDisonible")
                        .HasColumnType("real")
                        .HasColumnName("cantidadDisonible");

                    b.HasKey("Idstock")
                        .HasName("PK_stock_idstock");

                    b.ToTable("stock", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<short?>("Active")
                        .HasColumnType("smallint")
                        .HasColumnName("active");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "user$email")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("QuezalliApi.Models.UsersRole", b =>
                {
                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("roleId");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.ToTable("users_roles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
